// client/src/components/landing/vision.tsx
import { motion } from "framer-motion";
import { Shield, Target, Users, Award } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

const visionPoints = [
  {
    title: "Our Mission",
    description: "To empower sneaker resellers with expert resources and insights, helping them generate sustainable profits in the competitive reselling market.",
    icon: Target
  },
  {
    title: "Our Values",
    description: "We believe in transparency, community support, and continuous innovation to keep our members ahead of market trends.",
    icon: Shield
  },
  {
    title: "Our Community",
    description: "Building a supportive network of successful resellers who share knowledge and grow together.",
    icon: Users
  },
  {
    title: "Our Commitment",
    description: "Ensuring our members stay ahead of trends, maximize profits, and remain confident in their success journey.",
    icon: Award
  }
];

export default function Vision() {
  return (
    <section className="py-24 bg-gradient-to-b from-white to-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          className="text-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
        >
          <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
            Our Vision for Success
          </h2>
          <p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">
            Since 2017, we've been dedicated to transforming sneaker reselling into a profitable venture for our community
          </p>
        </motion.div>

        <div className="mt-16 grid grid-cols-1 gap-8 md:grid-cols-2">
          {visionPoints.map((point, index) => (
            <motion.div
              key={point.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1 }}
            >
              <Card className="h-full hover:shadow-lg transition-shadow duration-300">
                <CardContent className="p-6">
                  <div className="flex items-center space-x-4">
                    <div className="p-3 bg-blue-100 rounded-lg">
                      <point.icon className="h-6 w-6 text-blue-600" />
                    </div>
                    <h3 className="text-xl font-semibold text-gray-900">
                      {point.title}
                    </h3>
                  </div>
                  <p className="mt-4 text-gray-600 leading-relaxed">
                    {point.description}
                  </p>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

// src/lib/components/landing/Vision.svelte
<script>
  import { fly } from 'svelte/transition';
  import { Target, Zap, Users, Shield } from 'lucide-svelte';

  const visionPoints = [
    {
      title: "Expert-Driven Success",
      description: "Learn from industry veterans with proven track records in sneaker reselling",
      icon: Target
    },
    {
      title: "Cutting-Edge Tools",
      description: "Access advanced monitoring and automation tools that give you the competitive edge",
      icon: Zap
    },
    {
      title: "Supportive Community",
      description: "Join an exclusive network of successful resellers sharing insights and strategies",
      icon: Users
    },
    {
      title: "Proven Systems",
      description: "Follow battle-tested methods that consistently generate profits on every release",
      icon: Shield
    }
  ];
</script>

<section class="py-24 bg-gradient-to-b from-white to-gray-50">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div 
      in:fly={{ y: 20, duration: 500 }}
      class="text-center max-w-3xl mx-auto"
    >
      <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
        Transform Your Reselling Journey
      </h2>
      <p class="mt-4 text-lg text-gray-600">
        Join AK CHEFS and gain access to the tools, knowledge, and community you need to succeed in the competitive world of sneaker reselling
      </p>
    </div>

    <div class="mt-16 grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-4">
      {#each visionPoints as point, i}
        <div
          in:fly={{ y: 20, duration: 500, delay: i * 100 }}
          class="relative group"
        >
          <div class="absolute inset-0 bg-gradient-to-r from-blue-50 to-white rounded-lg transform group-hover:scale-105 transition-transform duration-300"></div>
          <div class="relative p-6 bg-white rounded-lg shadow-sm group-hover:shadow-lg transition-shadow duration-300">
            <div class="p-3 bg-blue-100 rounded-lg w-12 h-12 flex items-center justify-center mb-4">
              <svelte:component this={point.icon} class="h-6 w-6 text-blue-600" />
            </div>
            <h3 class="text-lg font-semibold text-gray-900 mb-2">{point.title}</h3>
            <p class="text-gray-600">{point.description}</p>
          </div>
        </div>
      {/each}
    </div>
  </div>
</section>
